name = "Dogsay"
uuid = "e4b88ea9-8232-438f-beaa-39e5d53fd5fe"
authors = ["Rakshit Naidu <rakshit.naidu07@gmail.com>"]
version = "0.1.0"

[compat]
julia = ">= 0.7"

[extras]
Test = "6fcba20b-dca0-4f82-a158-75077b90db52"

[targets]
test = ["Test"]

