name = "Dogsay"
uuid = "e4b88ea9-8232-438f-beaa-39e5d53fd5fe"
authors = ["Rakshit Naidu <rakshit.naidu07@gmail.com>"]
version = "0.1.0"

[deps]
Dogsay = "e4b88ea9-8232-438f-beaa-39e5d53fd5fe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "<= 1.4.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
