name = "Dogsay"
uuid = "9013e978-0fa9-4a6f-8e4e-e4657e80fe81"
authors = ["Rakshit Naidu <rakshit.naidu07@gmail.com>"]
version = "0.1.0"

[compat]
julia = ">= 0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
build = ["Libdl"]


