name = "Dogsay"
uuid = "5193907d-d586-5f94-a3e6-8b6fe67f210a"
authors = ["Rakshit Naidu <rakshit.naidu07@gmail.com>"]
version = "0.1.0"

[compat]
julia = ">= 0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

